configured_endpoints: 187
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hanzo-industries-inc%2Fhanzo-ai-240daacf60ba04cc18807e6264dfc0f2271ae68afff4dd5098aecf7fdb62e1cc.yml
openapi_spec_hash: 0f43453f97aa3a983038bbf7172cff51
config_hash: e927bafd76a1eace11894efc3517d245
