#!/bin/bash
# COPY AND PASTE THESE COMMANDS INTO YOUR TERMINAL

echo "════════════════════════════════════════════════════════════"
echo "     HANZO DEV - TERMINAL COMMANDS YOU CAN RUN NOW"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "1️⃣  BASIC GPT-5 (Default):"
echo "────────────────────────────"
echo "hanzo dev"
echo ""
echo "2️⃣  GPT-5 PRO + CODEX (Best for code):"
echo "────────────────────────────────────────"
echo "hanzo dev --orchestrator gpt-5-pro-codex"
echo ""
echo "3️⃣  ROUTER MODE (Via hanzo-router):"
echo "──────────────────────────────────────"
echo "# First start router:"
echo "hanzo router start"
echo "# Then:"
echo "hanzo dev --orchestrator router:gpt-4o"
echo ""
echo "4️⃣  DIRECT CODEX (Code generation):"
echo "──────────────────────────────────────"
echo "hanzo dev --orchestrator codex"
echo ""
echo "5️⃣  COST-OPTIMIZED (90% savings):"
echo "────────────────────────────────────"
echo "# First start local AI:"
echo "hanzo net --models llama-3.2-3b"
echo "# Then:"
echo "hanzo dev --orchestrator cost-optimized --use-hanzo-net"
echo ""
echo "6️⃣  LOCAL ONLY (Free!):"
echo "──────────────────────"
echo "hanzo dev --orchestrator local:llama3.2"
echo ""
echo "7️⃣  CUSTOM CONFIGURATIONS:"
echo "─────────────────────────────"
echo "# Force router mode:"
echo "hanzo dev --orchestrator-mode router --orchestrator gpt-5"
echo ""
echo "# Force direct mode:"
echo "hanzo dev --orchestrator-mode direct --orchestrator gpt-4o"
echo ""
echo "# Custom router endpoint:"
echo "hanzo dev --router-endpoint http://localhost:8080 --orchestrator router:gpt-5"
echo ""
echo "# More workers:"
echo "hanzo dev --orchestrator gpt-5-pro-codex --instances 5"
echo ""
echo "# With monitoring:"
echo "hanzo dev --orchestrator gpt-5-pro-codex --monitor"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 COPY ANY COMMAND ABOVE AND PASTE INTO YOUR TERMINAL!"
echo ""
echo "Example session:"
echo "$ hanzo dev --orchestrator gpt-5-pro-codex"
echo "> review my code for security issues"
echo "> generate a REST API with authentication"
echo "> add tests to the user service"
echo "> optimize this database query"
echo ""
echo "════════════════════════════════════════════════════════════"