# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from typing import Dict
from typing_extensions import Literal, Required, TypedDict

__all__ = ["UtilTransformRequestParams"]


class UtilTransformRequestParams(TypedDict, total=False):
    call_type: Required[
        Literal[
            "embedding",
            "aembedding",
            "completion",
            "acompletion",
            "atext_completion",
            "text_completion",
            "image_generation",
            "aimage_generation",
            "image_edit",
            "aimage_edit",
            "moderation",
            "amoderation",
            "atranscription",
            "transcription",
            "aspeech",
            "speech",
            "rerank",
            "arerank",
            "search",
            "asearch",
            "_arealtime",
            "create_batch",
            "acreate_batch",
            "aretrieve_batch",
            "retrieve_batch",
            "pass_through_endpoint",
            "anthropic_messages",
            "get_assistants",
            "aget_assistants",
            "create_assistants",
            "acreate_assistants",
            "delete_assistant",
            "adelete_assistant",
            "acreate_thread",
            "create_thread",
            "aget_thread",
            "get_thread",
            "a_add_message",
            "add_message",
            "aget_messages",
            "get_messages",
            "arun_thread",
            "run_thread",
            "arun_thread_stream",
            "run_thread_stream",
            "afile_retrieve",
            "file_retrieve",
            "afile_delete",
            "file_delete",
            "afile_list",
            "file_list",
            "acreate_file",
            "create_file",
            "afile_content",
            "file_content",
            "create_fine_tuning_job",
            "acreate_fine_tuning_job",
            "create_video",
            "acreate_video",
            "avideo_retrieve",
            "video_retrieve",
            "avideo_content",
            "video_content",
            "video_remix",
            "avideo_remix",
            "video_list",
            "avideo_list",
            "video_retrieve_job",
            "avideo_retrieve_job",
            "video_delete",
            "avideo_delete",
            "vector_store_file_create",
            "avector_store_file_create",
            "vector_store_file_list",
            "avector_store_file_list",
            "vector_store_file_retrieve",
            "avector_store_file_retrieve",
            "vector_store_file_content",
            "avector_store_file_content",
            "vector_store_file_update",
            "avector_store_file_update",
            "vector_store_file_delete",
            "avector_store_file_delete",
            "vector_store_create",
            "avector_store_create",
            "vector_store_search",
            "avector_store_search",
            "create_container",
            "acreate_container",
            "list_containers",
            "alist_containers",
            "retrieve_container",
            "aretrieve_container",
            "delete_container",
            "adelete_container",
            "list_container_files",
            "alist_container_files",
            "upload_container_file",
            "aupload_container_file",
            "acancel_fine_tuning_job",
            "cancel_fine_tuning_job",
            "alist_fine_tuning_jobs",
            "list_fine_tuning_jobs",
            "aretrieve_fine_tuning_job",
            "retrieve_fine_tuning_job",
            "responses",
            "aresponses",
            "alist_input_items",
            "llm_passthrough_route",
            "allm_passthrough_route",
            "generate_content",
            "agenerate_content",
            "generate_content_stream",
            "agenerate_content_stream",
            "ocr",
            "aocr",
            "call_mcp_tool",
            "asend_message",
            "send_message",
            "acreate_skill",
        ]
    ]

    request_body: Required[Dict[str, object]]
