# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.account_key_budget import AccountKeyBudget
from typing import Optional, Set
from typing_extensions import Self

class AccountKeyEdit(BaseModel):
    """
    AccountKeyEdit
    """ # noqa: E501
    budget: Optional[AccountKeyBudget] = Field(default=None, description="Budget replaces the key's spend caps, in cents; a zero drops that cap.")
    expires: Optional[StrictStr] = Field(default=None, description="Expires replaces when the key stops working, RFC 3339. An empty string means never.")
    id: Optional[StrictStr] = Field(default=None, description="ID is the key to edit, from the path.")
    limit: Optional[List[StrictStr]] = Field(default=None, description="Limit replaces what the key may reach. An empty list makes it unrestricted.")
    name: Optional[StrictStr] = Field(default=None, description="Name relabels the key.")
    rate: Optional[StrictInt] = Field(default=None, description="Rate replaces the key's requests a minute; zero drops the limit.")
    __properties: ClassVar[List[str]] = ["budget", "expires", "id", "limit", "name", "rate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AccountKeyEdit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of budget
        if self.budget:
            _dict['budget'] = self.budget.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AccountKeyEdit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "budget": AccountKeyBudget.from_dict(obj["budget"]) if obj.get("budget") is not None else None,
            "expires": obj.get("expires"),
            "id": obj.get("id"),
            "limit": obj.get("limit"),
            "name": obj.get("name"),
            "rate": obj.get("rate")
        })
        return _obj


