# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.ai_action import AiAction
from hanzoai.cloud.models.ai_class import AiClass
from hanzoai.cloud.models.ai_limited import AiLimited
from hanzoai.cloud.models.ai_paused import AiPaused
from hanzoai.cloud.models.ai_window import AiWindow
from typing import Optional, Set
from typing_extensions import Self

class AiLimits(BaseModel):
    """
    AiLimits
    """ # noqa: E501
    actions: Optional[List[AiAction]] = Field(default=None, description="Actions are the ways on: upgrade, add prepaid credit.")
    classes: Optional[Dict[str, AiClass]] = Field(default=None, description="Classes are premium (third-party frontier models) and ours (Hanzo's), each present when the plan includes it.")
    credits_after_allowance: Optional[StrictBool] = Field(default=None, description="CreditsAfterAllowance is the payer's choice to keep using a model on credits once the plan's included usage of it is spent (PUT /v1/ai/limits sets it).")
    day: Optional[AiWindow] = None
    limited: Optional[AiLimited] = Field(default=None, description="Limited is present in limited mode.")
    paused: Optional[List[AiPaused]] = Field(default=None, description="Paused are the models whose share of the plan is used for now: each is answered by its fallback in chat until its share resets.")
    period_end: Optional[StrictStr] = None
    period_start: Optional[StrictStr] = Field(default=None, description="PeriodStart and PeriodEnd bound the billing period (RFC3339).")
    plan: Optional[StrictStr] = Field(default=None, description="Plan is the plan the caller is served as (\"dev\", \"max-5x\", \"max-20x\", \"team\", \"team-annual\", \"agency\", \"advisory\", \"dedicated\", ...), \"free\" when none counts.")
    session: Optional[AiWindow] = Field(default=None, description="Session and Day are the request windows over every request the plan covers.")
    state: Optional[StrictStr] = Field(default=None, description="State is the worst class's: ok, near or limited.")
    upgrade: Optional[StrictStr] = Field(default=None, description="Upgrade is the plan that raises these limits, absent at the top.")
    __properties: ClassVar[List[str]] = ["actions", "classes", "credits_after_allowance", "day", "limited", "paused", "period_end", "period_start", "plan", "session", "state", "upgrade"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AiLimits from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict['actions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each value in classes (dict)
        _field_dict = {}
        if self.classes:
            for _key_classes in self.classes:
                if self.classes[_key_classes]:
                    _field_dict[_key_classes] = self.classes[_key_classes].to_dict()
            _dict['classes'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of day
        if self.day:
            _dict['day'] = self.day.to_dict()
        # override the default output from pydantic by calling `to_dict()` of limited
        if self.limited:
            _dict['limited'] = self.limited.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in paused (list)
        _items = []
        if self.paused:
            for _item_paused in self.paused:
                if _item_paused:
                    _items.append(_item_paused.to_dict())
            _dict['paused'] = _items
        # override the default output from pydantic by calling `to_dict()` of session
        if self.session:
            _dict['session'] = self.session.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AiLimits from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "actions": [AiAction.from_dict(_item) for _item in obj["actions"]] if obj.get("actions") is not None else None,
            "classes": dict(
                (_k, AiClass.from_dict(_v))
                for _k, _v in obj["classes"].items()
            )
            if obj.get("classes") is not None
            else None,
            "credits_after_allowance": obj.get("credits_after_allowance"),
            "day": AiWindow.from_dict(obj["day"]) if obj.get("day") is not None else None,
            "limited": AiLimited.from_dict(obj["limited"]) if obj.get("limited") is not None else None,
            "paused": [AiPaused.from_dict(_item) for _item in obj["paused"]] if obj.get("paused") is not None else None,
            "period_end": obj.get("period_end"),
            "period_start": obj.get("period_start"),
            "plan": obj.get("plan"),
            "session": AiWindow.from_dict(obj["session"]) if obj.get("session") is not None else None,
            "state": obj.get("state"),
            "upgrade": obj.get("upgrade")
        })
        return _obj


