# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CartItem(BaseModel):
    """
    CartItem
    """ # noqa: E501
    free: Optional[StrictBool] = Field(default=None, description="Free reports a line that costs nothing because a coupon or a promotion made it so, rather than because its price is zero.")
    id: Optional[StrictStr] = Field(default=None, description="ID is the line's identity — the variant id when the line is a variant, otherwise the product id. It is what a subsequent set call addresses.")
    kind: Optional[StrictStr] = Field(default=None, description="Kind is \"variant\" when this line is a specific sellable variant and \"product\" when it is the product itself.")
    name: Optional[StrictStr] = Field(default=None, description="Name is the item's display name, cached onto the line when it was added so a cart renders without a second read.")
    price_cents: Optional[StrictInt] = Field(default=None, description="PriceCents is the unit price in whole cents, cached at the moment the line was added. The line's contribution to the cart is this times Quantity.", alias="priceCents")
    quantity: Optional[StrictInt] = Field(default=None, description="Quantity is how many units of this item the cart holds.")
    sku: Optional[StrictStr] = Field(default=None, description="SKU is the line's stock-keeping unit — the variant's when it has one, otherwise the product's. Empty when neither carries one.")
    __properties: ClassVar[List[str]] = ["free", "id", "kind", "name", "priceCents", "quantity", "sku"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CartItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CartItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "free": obj.get("free"),
            "id": obj.get("id"),
            "kind": obj.get("kind"),
            "name": obj.get("name"),
            "priceCents": obj.get("priceCents"),
            "quantity": obj.get("quantity"),
            "sku": obj.get("sku")
        })
        return _obj


