# coding: utf-8

"""
    Hanzo Cloud — Unified API (V8 · Open Edition)

    The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

    The version of the OpenAPI document: 8.0.0
    Contact: support@hanzo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.cloud_screen_result import CloudScreenResult
from hanzoai.cloud.models.cloud_stage_event import CloudStageEvent
from typing import Optional, Set
from typing_extensions import Self

class CloudApplication(BaseModel):
    """
    CloudApplication
    """ # noqa: E501
    company: Optional[StrictStr] = Field(default=None, description="Company is the applicant's company name.")
    company_id: Optional[StrictStr] = Field(default=None, description="CompanyID is the CRM Company minted for this lead at intake, so the startup also appears in the org's standard CRM tabs. Empty when that best-effort projection did not run.", alias="companyId")
    contact_id: Optional[StrictStr] = Field(default=None, description="ContactID is the CRM Contact minted for this lead at intake. Empty when that best-effort projection did not run.", alias="contactId")
    contact_name: Optional[StrictStr] = Field(default=None, description="ContactName is the person who applied.", alias="contactName")
    created_at: Optional[StrictInt] = Field(default=None, description="CreatedAt is the unix second the application arrived. Server-owned.", alias="createdAt")
    email: Optional[StrictStr] = Field(default=None, description="Email is the applicant's email — half of the (email, company) key a resubmission refreshes instead of duplicating.")
    events: Optional[List[CloudStageEvent]] = Field(default=None, description="Events is the append-only stage-transition log, oldest first.")
    id: Optional[StrictStr] = Field(default=None, description="ID is the server-minted application id (\"appl_\" + 128 random bits).")
    metadata: Optional[Dict[str, Dict[str, Any]]] = Field(default=None, description="Metadata is the FULL submitted form, every field, including the arrays the promoted columns above do not carry (tier1Investors, useCases) and the deterministic tier1Matched list.")
    reason: Optional[StrictStr] = Field(default=None, description="Reason is why the application was rejected, required to reject. Empty otherwise.")
    role: Optional[StrictStr] = Field(default=None, description="Role is the applicant's role at their company.")
    screen: Optional[CloudScreenResult] = Field(default=None, description="Screen is the AI screen. It runs after intake, so a freshly created application carries a \"pending\" screen.")
    stage: Optional[StrictStr] = Field(default=None, description="Stage is the pipeline stage: applied, screened, qualified, credits-offered, onboarded or rejected. Server-owned — it starts at \"applied\" and moves only through the transition machine.")
    tier1: Optional[StrictBool] = Field(default=None, description="Tier1 is whether the applicant is tier-1 backed, derived deterministically at intake from the submitted fund list — independent of the AI screen.")
    updated_at: Optional[StrictInt] = Field(default=None, description="UpdatedAt is the unix second of the last write. Server-owned.", alias="updatedAt")
    website: Optional[StrictStr] = Field(default=None, description="Website is the applicant's website as submitted.")
    __properties: ClassVar[List[str]] = ["company", "companyId", "contactId", "contactName", "createdAt", "email", "events", "id", "metadata", "reason", "role", "screen", "stage", "tier1", "updatedAt", "website"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudApplication from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in events (list)
        _items = []
        if self.events:
            for _item_events in self.events:
                if _item_events:
                    _items.append(_item_events.to_dict())
            _dict['events'] = _items
        # override the default output from pydantic by calling `to_dict()` of screen
        if self.screen:
            _dict['screen'] = self.screen.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudApplication from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "company": obj.get("company"),
            "companyId": obj.get("companyId"),
            "contactId": obj.get("contactId"),
            "contactName": obj.get("contactName"),
            "createdAt": obj.get("createdAt"),
            "email": obj.get("email"),
            "events": [CloudStageEvent.from_dict(_item) for _item in obj["events"]] if obj.get("events") is not None else None,
            "id": obj.get("id"),
            "metadata": obj.get("metadata"),
            "reason": obj.get("reason"),
            "role": obj.get("role"),
            "screen": CloudScreenResult.from_dict(obj["screen"]) if obj.get("screen") is not None else None,
            "stage": obj.get("stage"),
            "tier1": obj.get("tier1"),
            "updatedAt": obj.get("updatedAt"),
            "website": obj.get("website")
        })
        return _obj


