# coding: utf-8

"""
    Hanzo Cloud — Unified API (V8 · Open Edition)

    The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). cloud/openapi.yaml is hanzoai/cloud's own woven document, copied verbatim by sync.py, and it wins wherever it and a hand-written spec describe the same route. Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

    The version of the OpenAPI document: 8.0.0
    Contact: support@hanzo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.cloud_version_view import CloudVersionView
from typing import Optional, Set
from typing_extensions import Self

class CloudPromptDetail(BaseModel):
    """
    CloudPromptDetail
    """ # noqa: E501
    created_at: Optional[StrictStr] = Field(default=None, alias="createdAt")
    labels: Optional[List[StrictStr]] = None
    last_updated_at: Optional[StrictStr] = Field(default=None, alias="lastUpdatedAt")
    name: Optional[StrictStr] = None
    prompt: Optional[StrictStr] = None
    tags: Optional[List[StrictStr]] = None
    type: Optional[StrictStr] = None
    version: Optional[StrictInt] = None
    version_history: Optional[List[CloudVersionView]] = Field(default=None, alias="versionHistory")
    __properties: ClassVar[List[str]] = ["createdAt", "labels", "lastUpdatedAt", "name", "prompt", "tags", "type", "version", "versionHistory"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudPromptDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in version_history (list)
        _items = []
        if self.version_history:
            for _item_version_history in self.version_history:
                if _item_version_history:
                    _items.append(_item_version_history.to_dict())
            _dict['versionHistory'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudPromptDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "labels": obj.get("labels"),
            "lastUpdatedAt": obj.get("lastUpdatedAt"),
            "name": obj.get("name"),
            "prompt": obj.get("prompt"),
            "tags": obj.get("tags"),
            "type": obj.get("type"),
            "version": obj.get("version"),
            "versionHistory": [CloudVersionView.from_dict(_item) for _item in obj["versionHistory"]] if obj.get("versionHistory") is not None else None
        })
        return _obj


