# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.cluster_view import ClusterView
from hanzoai.cloud.models.source_failure import SourceFailure
from typing import Optional, Set
from typing_extensions import Self

class ClusterList(BaseModel):
    """
    ClusterList
    """ # noqa: E501
    clusters: Optional[List[ClusterView]] = Field(default=None, description="Clusters is the merged fleet — kind \"managed\" for Visor-provisioned, \"byo\" for an attached kubeconfig.")
    degraded: Optional[List[SourceFailure]] = Field(default=None, description="Degraded names any source that did not answer, so an empty Clusters means \"you have none\" only when this is absent. Omitted when everything answered, so a healthy response is unchanged. See degraded.go.")
    __properties: ClassVar[List[str]] = ["clusters", "degraded"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in clusters (list)
        _items = []
        if self.clusters:
            for _item_clusters in self.clusters:
                if _item_clusters:
                    _items.append(_item_clusters.to_dict())
            _dict['clusters'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in degraded (list)
        _items = []
        if self.degraded:
            for _item_degraded in self.degraded:
                if _item_degraded:
                    _items.append(_item_degraded.to_dict())
            _dict['degraded'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "clusters": [ClusterView.from_dict(_item) for _item in obj["clusters"]] if obj.get("clusters") is not None else None,
            "degraded": [SourceFailure.from_dict(_item) for _item in obj["degraded"]] if obj.get("degraded") is not None else None
        })
        return _obj


