# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.customer_txn import CustomerTxn
from hanzoai.cloud.models.customer_user import CustomerUser
from typing import Optional, Set
from typing_extensions import Self

class CustomerDetailData(BaseModel):
    """
    CustomerDetailData
    """ # noqa: E501
    api_keys: Optional[StrictInt] = Field(default=None, alias="apiKeys")
    balance_cents: Optional[StrictInt] = Field(default=None, alias="balanceCents")
    created: Optional[StrictStr] = None
    display: Optional[StrictStr] = None
    mrr_cents: Optional[StrictInt] = Field(default=None, alias="mrrCents")
    org: Optional[StrictStr] = None
    owner_email: Optional[StrictStr] = Field(default=None, alias="ownerEmail")
    plan: Optional[StrictStr] = None
    spend_cents: Optional[StrictInt] = Field(default=None, alias="spendCents")
    status: Optional[StrictStr] = None
    transactions: Optional[List[CustomerTxn]] = None
    users: Optional[List[CustomerUser]] = None
    __properties: ClassVar[List[str]] = ["apiKeys", "balanceCents", "created", "display", "mrrCents", "org", "ownerEmail", "plan", "spendCents", "status", "transactions", "users"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerDetailData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item_transactions in self.transactions:
                if _item_transactions:
                    _items.append(_item_transactions.to_dict())
            _dict['transactions'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in users (list)
        _items = []
        if self.users:
            for _item_users in self.users:
                if _item_users:
                    _items.append(_item_users.to_dict())
            _dict['users'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerDetailData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "apiKeys": obj.get("apiKeys"),
            "balanceCents": obj.get("balanceCents"),
            "created": obj.get("created"),
            "display": obj.get("display"),
            "mrrCents": obj.get("mrrCents"),
            "org": obj.get("org"),
            "ownerEmail": obj.get("ownerEmail"),
            "plan": obj.get("plan"),
            "spendCents": obj.get("spendCents"),
            "status": obj.get("status"),
            "transactions": [CustomerTxn.from_dict(_item) for _item in obj["transactions"]] if obj.get("transactions") is not None else None,
            "users": [CustomerUser.from_dict(_item) for _item in obj["users"]] if obj.get("users") is not None else None
        })
        return _obj


