# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GithubRepoView(BaseModel):
    """
    GithubRepoView
    """ # noqa: E501
    default_branch: Optional[StrictStr] = Field(default=None, description="DefaultBranch is the repo's default branch at GitHub.", alias="defaultBranch")
    full_name: Optional[StrictStr] = Field(default=None, description="FullName is GitHub's owner/name.", alias="fullName")
    html_url: Optional[StrictStr] = Field(default=None, description="HTMLURL is the repo's page at GitHub.", alias="htmlUrl")
    imported: Optional[StrictBool] = Field(default=None, description="Imported is whether this repo has been mirrored into git.hanzo.ai.")
    last_synced_at: Optional[StrictStr] = Field(default=None, description="LastSyncedAt is the last successful mirror, RFC 3339 UTC. Absent if never.", alias="lastSyncedAt")
    name: Optional[StrictStr] = Field(default=None, description="Name is the repository's short name within the installation.")
    private: Optional[StrictBool] = Field(default=None, description="Private is GitHub's visibility bit for the repo.")
    sync_status: Optional[StrictStr] = Field(default=None, description="SyncStatus is \"synced\", \"conflict\", or \"\" when the repo is not imported.", alias="syncStatus")
    __properties: ClassVar[List[str]] = ["defaultBranch", "fullName", "htmlUrl", "imported", "lastSyncedAt", "name", "private", "syncStatus"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GithubRepoView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GithubRepoView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "defaultBranch": obj.get("defaultBranch"),
            "fullName": obj.get("fullName"),
            "htmlUrl": obj.get("htmlUrl"),
            "imported": obj.get("imported"),
            "lastSyncedAt": obj.get("lastSyncedAt"),
            "name": obj.get("name"),
            "private": obj.get("private"),
            "syncStatus": obj.get("syncStatus")
        })
        return _obj


