# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.graph_graph_finding import GraphGraphFinding
from typing import Optional, Set
from typing_extensions import Self

class GraphGraphAnswerOut(BaseModel):
    """
    GraphGraphAnswerOut
    """ # noqa: E501
    answer: Optional[StrictStr] = Field(default=None, description="Answer is the answer, in prose.")
    as_known: Optional[StrictStr] = Field(default=None, description="AsKnown is the knowledge instant it was taken at, RFC 3339, the same way.")
    as_of: Optional[StrictStr] = Field(default=None, description="AsOf is the instant the graph was read at, RFC 3339: the one asked for, or the server's clock when none was.")
    asked: Optional[StrictInt] = Field(default=None, description="Asked is how many communities were read.")
    assertions: Optional[List[StrictStr]] = Field(default=None, description="Assertions are the IDs of every assertion the answer rests on, ascending.")
    calls: Optional[StrictInt] = Field(default=None, description="Calls is how many model calls the answer made, each billed to the calling organization.")
    clipped: Optional[StrictBool] = Field(default=None, description="Clipped says the answer did not read all it gathered: a community held more facts than one call carries, or more members than one answer reads, and kept the ones the question named and then the most connected; a member held more than 64 assertions and kept its newest; or the findings held more than the answering call carries and kept the highest scored.")
    communities: Optional[List[StrictInt]] = Field(default=None, description="Communities are every community the answer rests on, ascending.")
    findings: Optional[List[GraphGraphFinding]] = Field(default=None, description="Findings are the findings the answer cites, most relevant first.")
    grounded: Optional[StrictBool] = Field(default=None, description="Grounded is false when no community held a fact bearing on the question, or the findings did not answer it. Answer is then empty: an answer resting on nothing is not one this plane gives.")
    skipped: Optional[StrictInt] = Field(default=None, description="Skipped is how many were not, because one answer makes at most eight map calls and reads at most 2048 entities. They are the ones the question's words ranked last.")
    __properties: ClassVar[List[str]] = ["answer", "as_known", "as_of", "asked", "assertions", "calls", "clipped", "communities", "findings", "grounded", "skipped"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GraphGraphAnswerOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in findings (list)
        _items = []
        if self.findings:
            for _item_findings in self.findings:
                if _item_findings:
                    _items.append(_item_findings.to_dict())
            _dict['findings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GraphGraphAnswerOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "answer": obj.get("answer"),
            "as_known": obj.get("as_known"),
            "as_of": obj.get("as_of"),
            "asked": obj.get("asked"),
            "assertions": obj.get("assertions"),
            "calls": obj.get("calls"),
            "clipped": obj.get("clipped"),
            "communities": obj.get("communities"),
            "findings": [GraphGraphFinding.from_dict(_item) for _item in obj["findings"]] if obj.get("findings") is not None else None,
            "grounded": obj.get("grounded"),
            "skipped": obj.get("skipped")
        })
        return _obj


