# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InboxView(BaseModel):
    """
    InboxView
    """ # noqa: E501
    account: Optional[StrictStr] = None
    channel: Optional[StrictStr] = None
    created_at: Optional[StrictInt] = Field(default=None, alias="createdAt")
    id: Optional[StrictInt] = None
    reply_to: Optional[StrictStr] = Field(default=None, alias="replyTo")
    room_id: Optional[StrictStr] = Field(default=None, alias="roomId")
    room_kind: Optional[StrictStr] = Field(default=None, alias="roomKind")
    sender: Optional[StrictStr] = None
    sender_user: Optional[StrictStr] = Field(default=None, alias="senderUser")
    text: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["account", "channel", "createdAt", "id", "replyTo", "roomId", "roomKind", "sender", "senderUser", "text"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InboxView from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InboxView from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account": obj.get("account"),
            "channel": obj.get("channel"),
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "replyTo": obj.get("replyTo"),
            "roomId": obj.get("roomId"),
            "roomKind": obj.get("roomKind"),
            "sender": obj.get("sender"),
            "senderUser": obj.get("senderUser"),
            "text": obj.get("text")
        })
        return _obj


