# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.figure import Figure
from typing import Optional, Set
from typing_extensions import Self

class MetricsResponse(BaseModel):
    """
    MetricsResponse
    """ # noqa: E501
    arr: Optional[StrictInt] = Field(default=None, description="ARR is annualized recurring revenue in cents (MRR × 12).")
    burn: Optional[StrictInt] = Field(default=None, description="Burn is total expense in cents over the period.")
    cash: Optional[StrictInt] = Field(default=None, description="Cash is the bank + processor-clearing balance in cents as of To.")
    cogs: Optional[StrictInt] = Field(default=None, description="COGS is cost of goods sold in cents over the period.")
    deferred_revenue: Optional[StrictInt] = Field(default=None, description="DeferredRevenue is the customer-wallet liability in cents as of To.", alias="deferredRevenue")
    figures: Optional[List[Figure]] = Field(default=None, description="Figures is the same snapshot rendered through books' one money formatter.")
    var_from: Optional[StrictStr] = Field(default=None, description="From is the RFC3339 start of the reporting window, exclusive; absent for all time.", alias="from")
    gross_margin_bps: Optional[StrictInt] = Field(default=None, description="GrossMarginBps is GrossProfit / Revenue in basis points (7000 = 70%).", alias="grossMarginBps")
    gross_profit: Optional[StrictInt] = Field(default=None, description="GrossProfit is Revenue − COGS, in cents.", alias="grossProfit")
    monthly_burn: Optional[StrictInt] = Field(default=None, description="MonthlyBurn is net cash burned per month in cents; 0 when not losing cash.", alias="monthlyBurn")
    months: Optional[StrictInt] = Field(default=None, description="Months is the window length in whole months used to normalize MRR and burn.")
    mrr: Optional[StrictInt] = Field(default=None, description="MRR is monthly recurring revenue in cents.")
    net_income: Optional[StrictInt] = Field(default=None, description="NetIncome is Revenue − Burn, in cents.", alias="netIncome")
    period: Optional[StrictStr] = Field(default=None, description="Period is the human window label, e.g. \"2026-07\" or \"all-time\".")
    revenue: Optional[StrictInt] = Field(default=None, description="Revenue is recognized revenue in cents over the period.")
    runway_months: Optional[StrictInt] = Field(default=None, description="RunwayMonths is Cash / MonthlyBurn; -1 means infinite (the org is not burning).", alias="runwayMonths")
    to: Optional[StrictStr] = Field(default=None, description="To is the RFC3339 end of the reporting window, inclusive; absent for up to now.")
    __properties: ClassVar[List[str]] = ["arr", "burn", "cash", "cogs", "deferredRevenue", "figures", "from", "grossMarginBps", "grossProfit", "monthlyBurn", "months", "mrr", "netIncome", "period", "revenue", "runwayMonths", "to"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetricsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in figures (list)
        _items = []
        if self.figures:
            for _item_figures in self.figures:
                if _item_figures:
                    _items.append(_item_figures.to_dict())
            _dict['figures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetricsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "arr": obj.get("arr"),
            "burn": obj.get("burn"),
            "cash": obj.get("cash"),
            "cogs": obj.get("cogs"),
            "deferredRevenue": obj.get("deferredRevenue"),
            "figures": [Figure.from_dict(_item) for _item in obj["figures"]] if obj.get("figures") is not None else None,
            "from": obj.get("from"),
            "grossMarginBps": obj.get("grossMarginBps"),
            "grossProfit": obj.get("grossProfit"),
            "monthlyBurn": obj.get("monthlyBurn"),
            "months": obj.get("months"),
            "mrr": obj.get("mrr"),
            "netIncome": obj.get("netIncome"),
            "period": obj.get("period"),
            "revenue": obj.get("revenue"),
            "runwayMonths": obj.get("runwayMonths"),
            "to": obj.get("to")
        })
        return _obj


