# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.o11y_filter import O11yFilter
from hanzoai.cloud.models.o11y_group_by_key import O11yGroupByKey
from hanzoai.cloud.models.o11y_querybuildertypesv5_order_by import O11yQuerybuildertypesv5OrderBy
from typing import Optional, Set
from typing_extensions import Self

class O11yPostableClusters(BaseModel):
    """
    O11yPostableClusters
    """ # noqa: E501
    end: Optional[StrictInt] = None
    filter: Optional[O11yFilter] = None
    group_by: Optional[List[O11yGroupByKey]] = Field(default=None, alias="groupBy")
    limit: Optional[StrictInt] = None
    offset: Optional[StrictInt] = None
    order_by: Optional[O11yQuerybuildertypesv5OrderBy] = Field(default=None, alias="orderBy")
    start: Optional[StrictInt] = None
    __properties: ClassVar[List[str]] = ["end", "filter", "groupBy", "limit", "offset", "orderBy", "start"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yPostableClusters from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of filter
        if self.filter:
            _dict['filter'] = self.filter.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in group_by (list)
        _items = []
        if self.group_by:
            for _item_group_by in self.group_by:
                if _item_group_by:
                    _items.append(_item_group_by.to_dict())
            _dict['groupBy'] = _items
        # override the default output from pydantic by calling `to_dict()` of order_by
        if self.order_by:
            _dict['orderBy'] = self.order_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yPostableClusters from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "end": obj.get("end"),
            "filter": O11yFilter.from_dict(obj["filter"]) if obj.get("filter") is not None else None,
            "groupBy": [O11yGroupByKey.from_dict(_item) for _item in obj["groupBy"]] if obj.get("groupBy") is not None else None,
            "limit": obj.get("limit"),
            "offset": obj.get("offset"),
            "orderBy": O11yQuerybuildertypesv5OrderBy.from_dict(obj["orderBy"]) if obj.get("orderBy") is not None else None,
            "start": obj.get("start")
        })
        return _obj


