# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.o11y_format_options import O11yFormatOptions
from hanzoai.cloud.models.o11y_querybuildertypesv5_composite_query import O11yQuerybuildertypesv5CompositeQuery
from hanzoai.cloud.models.o11y_variable_item import O11yVariableItem
from typing import Optional, Set
from typing_extensions import Self

class O11yQueryRangeRequest(BaseModel):
    """
    O11yQueryRangeRequest
    """ # noqa: E501
    composite_query: Optional[O11yQuerybuildertypesv5CompositeQuery] = Field(default=None, description="CompositeQuery is the composite query to use for the request.", alias="compositeQuery")
    end: Optional[StrictInt] = Field(default=None, description="End is the end time of the query in epoch milliseconds.")
    format_options: Optional[O11yFormatOptions] = Field(default=None, alias="formatOptions")
    no_cache: Optional[StrictBool] = Field(default=None, description="NoCache is a flag to disable caching for the request.", alias="noCache")
    request_type: Optional[Any] = Field(default=None, alias="requestType")
    schema_version: Optional[StrictStr] = Field(default=None, description="SchemaVersion is the version of the schema to use for the request payload.", alias="schemaVersion")
    start: Optional[StrictInt] = Field(default=None, description="Start is the start time of the query in epoch milliseconds.")
    variables: Optional[Dict[str, O11yVariableItem]] = Field(default=None, description="Variables is the variables to use for the request.")
    __properties: ClassVar[List[str]] = ["compositeQuery", "end", "formatOptions", "noCache", "requestType", "schemaVersion", "start", "variables"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yQueryRangeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of composite_query
        if self.composite_query:
            _dict['compositeQuery'] = self.composite_query.to_dict()
        # override the default output from pydantic by calling `to_dict()` of format_options
        if self.format_options:
            _dict['formatOptions'] = self.format_options.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in variables (dict)
        _field_dict = {}
        if self.variables:
            for _key_variables in self.variables:
                if self.variables[_key_variables]:
                    _field_dict[_key_variables] = self.variables[_key_variables].to_dict()
            _dict['variables'] = _field_dict
        # set to None if request_type (nullable) is None
        # and model_fields_set contains the field
        if self.request_type is None and "request_type" in self.model_fields_set:
            _dict['requestType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yQueryRangeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "compositeQuery": O11yQuerybuildertypesv5CompositeQuery.from_dict(obj["compositeQuery"]) if obj.get("compositeQuery") is not None else None,
            "end": obj.get("end"),
            "formatOptions": O11yFormatOptions.from_dict(obj["formatOptions"]) if obj.get("formatOptions") is not None else None,
            "noCache": obj.get("noCache"),
            "requestType": obj.get("requestType"),
            "schemaVersion": obj.get("schemaVersion"),
            "start": obj.get("start"),
            "variables": dict(
                (_k, O11yVariableItem.from_dict(_v))
                for _k, _v in obj["variables"].items()
            )
            if obj.get("variables") is not None
            else None
        })
        return _obj


