# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.o11y_o11y_llm_rule_pricing import O11yO11yLLMRulePricing
from typing import Optional, Set
from typing_extensions import Self

class O11yO11yLLMPricingRule(BaseModel):
    """
    O11yO11yLLMPricingRule
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, description="CreatedAt is when the rule was stored.", alias="createdAt")
    created_by: Optional[StrictStr] = Field(default=None, description="CreatedBy is who created the rule.", alias="createdBy")
    enabled: Optional[StrictBool] = Field(default=None, description="Enabled says whether the rule is on.")
    id: Optional[StrictStr] = Field(default=None, description="ID is the rule's id.")
    is_override: Optional[StrictBool] = Field(default=None, description="IsOverride marks the rule user-pinned; when true the sync job skips it.", alias="isOverride")
    model_name: Optional[StrictStr] = Field(default=None, description="Model is the model the rule prices.", alias="modelName")
    model_pattern: Optional[List[StrictStr]] = Field(default=None, description="ModelPattern are the model-name globs the rule matches.", alias="modelPattern")
    org_id: Optional[StrictStr] = Field(default=None, description="OrgID is the org the rule belongs to.", alias="orgId")
    pricing: Optional[O11yO11yLLMRulePricing] = Field(default=None, description="Pricing is the per-unit cost.")
    provider: Optional[StrictStr] = Field(default=None, description="Provider is the model's provider.")
    source_id: Optional[StrictStr] = Field(default=None, description="SourceID is the upstream source the rule was synced from, when synced.", alias="sourceId")
    synced_at: Optional[datetime] = Field(default=None, description="SyncedAt is when the rule was last synced, when it is synced.", alias="syncedAt")
    unit: Optional[StrictStr] = Field(default=None, description="Unit is the pricing unit, e.g. per_million_tokens.")
    updated_at: Optional[datetime] = Field(default=None, description="UpdatedAt is when the rule last changed.", alias="updatedAt")
    updated_by: Optional[StrictStr] = Field(default=None, description="UpdatedBy is who last changed it.", alias="updatedBy")
    __properties: ClassVar[List[str]] = ["createdAt", "createdBy", "enabled", "id", "isOverride", "modelName", "modelPattern", "orgId", "pricing", "provider", "sourceId", "syncedAt", "unit", "updatedAt", "updatedBy"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yO11yLLMPricingRule from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of pricing
        if self.pricing:
            _dict['pricing'] = self.pricing.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yO11yLLMPricingRule from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "createdAt": obj.get("createdAt"),
            "createdBy": obj.get("createdBy"),
            "enabled": obj.get("enabled"),
            "id": obj.get("id"),
            "isOverride": obj.get("isOverride"),
            "modelName": obj.get("modelName"),
            "modelPattern": obj.get("modelPattern"),
            "orgId": obj.get("orgId"),
            "pricing": O11yO11yLLMRulePricing.from_dict(obj["pricing"]) if obj.get("pricing") is not None else None,
            "provider": obj.get("provider"),
            "sourceId": obj.get("sourceId"),
            "syncedAt": obj.get("syncedAt"),
            "unit": obj.get("unit"),
            "updatedAt": obj.get("updatedAt"),
            "updatedBy": obj.get("updatedBy")
        })
        return _obj


