# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.o11y_status_component import O11yStatusComponent
from typing import Optional, Set
from typing_extensions import Self

class O11yStatusMaintenance(BaseModel):
    """
    O11yStatusMaintenance
    """ # noqa: E501
    affected_components: Optional[List[O11yStatusComponent]] = None
    ends_at: Optional[StrictStr] = None
    id: Optional[StrictStr] = None
    last_update_at: Optional[StrictStr] = None
    last_update_message: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    starts_at: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    url: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["affected_components", "ends_at", "id", "last_update_at", "last_update_message", "name", "starts_at", "status", "url"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yStatusMaintenance from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in affected_components (list)
        _items = []
        if self.affected_components:
            for _item_affected_components in self.affected_components:
                if _item_affected_components:
                    _items.append(_item_affected_components.to_dict())
            _dict['affected_components'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yStatusMaintenance from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "affected_components": [O11yStatusComponent.from_dict(_item) for _item in obj["affected_components"]] if obj.get("affected_components") is not None else None,
            "ends_at": obj.get("ends_at"),
            "id": obj.get("id"),
            "last_update_at": obj.get("last_update_at"),
            "last_update_message": obj.get("last_update_message"),
            "name": obj.get("name"),
            "starts_at": obj.get("starts_at"),
            "status": obj.get("status"),
            "url": obj.get("url")
        })
        return _obj


