# coding: utf-8

"""
    Hanzo Cloud API

    Composed from each subsystem's own projection of its router, in the fleet's mount order — every operation below is a route the subsystem that publishes it registered. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class O11yTotals(BaseModel):
    """
    O11yTotals
    """ # noqa: E501
    completion_tokens: Optional[StrictInt] = Field(default=None, alias="completionTokens")
    cost_cents: Optional[StrictInt] = Field(default=None, alias="costCents")
    errors: Optional[StrictInt] = None
    latency_p50_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="latencyP50Ms")
    latency_p95_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="latencyP95Ms")
    latency_p99_ms: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, alias="latencyP99Ms")
    log_volume: Optional[StrictInt] = Field(default=None, description="Logs (event.log), fleet volume over the window.", alias="logVolume")
    models: Optional[StrictInt] = None
    orgs: Optional[StrictInt] = None
    prompt_tokens: Optional[StrictInt] = Field(default=None, alias="promptTokens")
    requests: Optional[StrictInt] = Field(default=None, description="LLM usage (hanzo.cloud_usage), all orgs.")
    services: Optional[StrictInt] = None
    tokens: Optional[StrictInt] = None
    trace_count: Optional[StrictInt] = Field(default=None, description="Traces (event.span), all services.", alias="traceCount")
    trace_error_rate: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="percent (0..100)", alias="traceErrorRate")
    __properties: ClassVar[List[str]] = ["completionTokens", "costCents", "errors", "latencyP50Ms", "latencyP95Ms", "latencyP99Ms", "logVolume", "models", "orgs", "promptTokens", "requests", "services", "tokens", "traceCount", "traceErrorRate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yTotals from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yTotals from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "completionTokens": obj.get("completionTokens"),
            "costCents": obj.get("costCents"),
            "errors": obj.get("errors"),
            "latencyP50Ms": obj.get("latencyP50Ms"),
            "latencyP95Ms": obj.get("latencyP95Ms"),
            "latencyP99Ms": obj.get("latencyP99Ms"),
            "logVolume": obj.get("logVolume"),
            "models": obj.get("models"),
            "orgs": obj.get("orgs"),
            "promptTokens": obj.get("promptTokens"),
            "requests": obj.get("requests"),
            "services": obj.get("services"),
            "tokens": obj.get("tokens"),
            "traceCount": obj.get("traceCount"),
            "traceErrorRate": obj.get("traceErrorRate")
        })
        return _obj


