# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.o11y_account_config import O11yAccountConfig
from hanzoai.cloud.models.o11y_agent_report import O11yAgentReport
from typing import Optional, Set
from typing_extensions import Self

class O11yAccount(BaseModel):
    """
    O11yAccount
    """ # noqa: E501
    agent_report: Optional[O11yAgentReport] = Field(default=None, alias="agentReport")
    config: Optional[O11yAccountConfig] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    id: Optional[Any] = None
    org_id: Optional[Any] = Field(default=None, alias="orgId")
    provider: Optional[Any] = None
    provider_account_id: Optional[StrictStr] = Field(default=None, alias="providerAccountId")
    removed_at: Optional[datetime] = Field(default=None, alias="removedAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    __properties: ClassVar[List[str]] = ["agentReport", "config", "createdAt", "id", "orgId", "provider", "providerAccountId", "removedAt", "updatedAt"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of O11yAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of agent_report
        if self.agent_report:
            _dict['agentReport'] = self.agent_report.to_dict()
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if org_id (nullable) is None
        # and model_fields_set contains the field
        if self.org_id is None and "org_id" in self.model_fields_set:
            _dict['orgId'] = None

        # set to None if provider (nullable) is None
        # and model_fields_set contains the field
        if self.provider is None and "provider" in self.model_fields_set:
            _dict['provider'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of O11yAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "agentReport": O11yAgentReport.from_dict(obj["agentReport"]) if obj.get("agentReport") is not None else None,
            "config": O11yAccountConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "createdAt": obj.get("createdAt"),
            "id": obj.get("id"),
            "orgId": obj.get("orgId"),
            "provider": obj.get("provider"),
            "providerAccountId": obj.get("providerAccountId"),
            "removedAt": obj.get("removedAt"),
            "updatedAt": obj.get("updatedAt")
        })
        return _obj


