# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from hanzoai.cloud.models.openai_audio_response_segments_inner import OpenaiAudioResponseSegmentsInner
from hanzoai.cloud.models.openai_audio_response_words_inner import OpenaiAudioResponseWordsInner
from typing import Optional, Set
from typing_extensions import Self

class OpenaiAudioResponse(BaseModel):
    """
    OpenaiAudioResponse
    """ # noqa: E501
    duration: Optional[Union[StrictFloat, StrictInt]] = None
    language: Optional[StrictStr] = None
    segments: Optional[List[OpenaiAudioResponseSegmentsInner]] = None
    task: Optional[StrictStr] = None
    text: Optional[StrictStr] = None
    words: Optional[List[OpenaiAudioResponseWordsInner]] = None
    __properties: ClassVar[List[str]] = ["duration", "language", "segments", "task", "text", "words"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of OpenaiAudioResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in segments (list)
        _items = []
        if self.segments:
            for _item_segments in self.segments:
                if _item_segments:
                    _items.append(_item_segments.to_dict())
            _dict['segments'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in words (list)
        _items = []
        if self.words:
            for _item_words in self.words:
                if _item_words:
                    _items.append(_item_words.to_dict())
            _dict['words'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of OpenaiAudioResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "duration": obj.get("duration"),
            "language": obj.get("language"),
            "segments": [OpenaiAudioResponseSegmentsInner.from_dict(_item) for _item in obj["segments"]] if obj.get("segments") is not None else None,
            "task": obj.get("task"),
            "text": obj.get("text"),
            "words": [OpenaiAudioResponseWordsInner.from_dict(_item) for _item in obj["words"]] if obj.get("words") is not None else None
        })
        return _obj


