# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PaymentRecord(BaseModel):
    """
    PaymentRecord
    """ # noqa: E501
    amount_cents: Optional[StrictInt] = Field(default=None, description="AmountCents is the credited amount in whole cents.", alias="amountCents")
    created_at: Optional[StrictStr] = Field(default=None, description="CreatedAt is when the credit was written, RFC3339.", alias="createdAt")
    currency: Optional[StrictStr] = Field(default=None, description="Currency is the ISO 4217 code.")
    id: Optional[StrictStr] = Field(default=None, description="ID is the ledger transaction id.")
    notes: Optional[StrictStr] = Field(default=None, description="Notes is the ledger memo, carrying the processor and its reference.")
    status: Optional[StrictStr] = Field(default=None, description="Status is the payment's state. This ledger writes a deposit only AFTER the processor settled, so a payment that can be read is one that succeeded.")
    subject: Optional[StrictStr] = Field(default=None, description="Subject is the billing key this payment credited.")
    test: Optional[StrictBool] = Field(default=None, description="Test reports whether this was a sandbox charge (test balance) or live money.")
    __properties: ClassVar[List[str]] = ["amountCents", "createdAt", "currency", "id", "notes", "status", "subject", "test"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentRecord from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentRecord from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "amountCents": obj.get("amountCents"),
            "createdAt": obj.get("createdAt"),
            "currency": obj.get("currency"),
            "id": obj.get("id"),
            "notes": obj.get("notes"),
            "status": obj.get("status"),
            "subject": obj.get("subject"),
            "test": obj.get("test")
        })
        return _obj


