# coding: utf-8

"""
    Hanzo Cloud — Unified API (V8 · Open Edition)

    The single unified OpenAPI surface for ALL Hanzo services, aggregated from the per-service specs. Every route is https://api.hanzo.ai/v1/<service>/*. Grouped by the canonical domains in capabilities.yaml (the ONE registry). Regenerated by merge.py — edit the per-service <svc>/openapi.yaml + capabilities.yaml, not this file.

    The version of the OpenAPI document: 8.0.0
    Contact: support@hanzo.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class PlatformGitProviderWebhookPayload(BaseModel):
    """
    Provider-specific webhook payload (GitHub/GitLab/Bitbucket/Gitea or Docker registry). Consumed untyped; the fields below are the commonly-read ones.
    """ # noqa: E501
    ref: Optional[StrictStr] = Field(default=None, description="GitHub/GitLab branch ref")
    after: Optional[StrictStr] = Field(default=None, description="Gitea/soft-serve post-push commit sha")
    checkout_sha: Optional[StrictStr] = Field(default=None, description="GitLab checkout sha")
    head_commit: Optional[Dict[str, Any]] = Field(default=None, description="GitHub head commit ({ id, message })")
    commits: Optional[List[Dict[str, Any]]] = Field(default=None, description="Commit list ({ id, message, modified })")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["ref", "after", "checkout_sha", "head_commit", "commits"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlatformGitProviderWebhookPayload from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlatformGitProviderWebhookPayload from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "ref": obj.get("ref"),
            "after": obj.get("after"),
            "checkout_sha": obj.get("checkout_sha"),
            "head_commit": obj.get("head_commit"),
            "commits": obj.get("commits")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


