# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay doors, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class ReviewRequest(BaseModel):
    """
    ReviewRequest
    """ # noqa: E501
    glossary: Optional[Dict[str, StrictStr]] = Field(default=None, description="Glossary is the terminology the entry was translated under. Its VERSION — the digest of the sorted terms — is part of the entry's identity, so editing a term yields a new entry rather than overwriting the old rendering.")
    source: Optional[StrictStr] = Field(default=None, description="Source is the ORIGINAL string this entry translates. Required; part of the entry's identity, so a different source is a different entry.")
    state: Optional[StrictStr] = Field(default=None, description="State is the entry's new position on the review ladder: suggested, approved or published. `machine` is engine-only and is refused here — a human may not demote a string back into the churn.")
    target: Optional[StrictStr] = Field(default=None, description="Target is the target language tag (BCP-47, e.g. \"es\" or \"pt-BR\"). Required; part of the entry's identity.")
    text: Optional[StrictStr] = Field(default=None, description="Text is the reviewed translation to store. A human write always wins over the stored value.")
    tier: Optional[StrictStr] = Field(default=None, description="Tier is the engine tier the entry belongs to, quality (the default) or bulk. Part of the entry's identity: the two tiers keep separate renderings.")
    __properties: ClassVar[List[str]] = ["glossary", "source", "state", "target", "text", "tier"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReviewRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReviewRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "glossary": obj.get("glossary"),
            "source": obj.get("source"),
            "state": obj.get("state"),
            "target": obj.get("target"),
            "text": obj.get("text"),
            "tier": obj.get("tier")
        })
        return _obj


