# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from hanzoai.cloud.models.risk_cause import RiskCause
from hanzoai.cloud.models.risk_value import RiskValue
from typing import Optional, Set
from typing_extensions import Self

class RiskScoreOut(BaseModel):
    """
    RiskScoreOut
    """ # noqa: E501
    alert: Optional[StrictBool] = Field(default=None, description="Alert is whether this would become evidence. It is false in shadow however high the score.")
    causes: Optional[List[RiskCause]] = Field(default=None, description="Causes is the per-feature attribution, ordered by contribution. Each is a COUNTERFACTUAL on the model that produced the score — the coordinate moved to its neutral value and the event rescored — so the explanation is the same arithmetic the score came from.")
    cut: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Cut is the threshold in force, derived from the stated appetite as a quantile of the scores actually observed rather than fixed at a number.")
    policy: Optional[StrictInt] = Field(default=None, description="Policy is the version of your organisation's decision regime this verdict was reached under, from its own policy history (GET /v1/risk/policy). Cut is derived from the appetite that version states, so it is the record that makes this decision reconstructible after the appetite is restated. Zero means no regime has ever been stated and the default posture — shadow — was in force.")
    refusal: Optional[StrictStr] = Field(default=None, description="Refusal names why the model declined, when it did.")
    score: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="Score is where the event sits in the tenant's own density: 0 where its recent behaviour is densest, 1 where there is none of it.")
    scored: Optional[StrictBool] = Field(default=None, description="Scored is false when the model declined, and Refusal says which refusal it was: warming, unusable or unidentified. None of them is a clean bill of health, which is why the refusal is stated rather than rendered as a score of zero.")
    shadow: Optional[StrictBool] = Field(default=None, description="Shadow is whether the model is testing rather than deciding — scoring, learning and recording what it WOULD have alerted on, and changing no outcome. It is the default for a model no one has reviewed yet.")
    shape: Optional[StrictStr] = Field(default=None, description="Shape is the model space this verdict was reached in, as `<family>:<digest>`: the KIND of model, and that family's own digest over your organisation's feature inventory in order and the detector's geometry parameters. It is what pins an adverse decision to a model — a score is only meaningful against the space that produced it, and without this the only answer to \"which model decided this\" was \"the one that was running\", which is not an answer.  The family leads it because everything after it is one family's arithmetic. Two spaces are the same space only if they are the same family, so comparing this with the `shape` on your model state or on a published value is a comparison that holds ACROSS families and not only inside one.  It names the SPACE, not the learned state, and that is deliberate. The masses at the instant of a score are in-process counters somewhere between two published values, so citing a published address here would claim that value produced this score — true only for the score taken the instant after a publication. This, the policy version and the event's own time are what IS true, and the published history's clock (GET /v1/risk/state) brackets the decision between two named values from there.")
    values: Optional[List[RiskValue]] = Field(default=None, description="Values is every coordinate, including the ones that contributed nothing, so a reviewer sees what the model read and not only what it concluded.")
    __properties: ClassVar[List[str]] = ["alert", "causes", "cut", "policy", "refusal", "score", "scored", "shadow", "shape", "values"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RiskScoreOut from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in causes (list)
        _items = []
        if self.causes:
            for _item_causes in self.causes:
                if _item_causes:
                    _items.append(_item_causes.to_dict())
            _dict['causes'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in values (list)
        _items = []
        if self.values:
            for _item_values in self.values:
                if _item_values:
                    _items.append(_item_values.to_dict())
            _dict['values'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RiskScoreOut from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "alert": obj.get("alert"),
            "causes": [RiskCause.from_dict(_item) for _item in obj["causes"]] if obj.get("causes") is not None else None,
            "cut": obj.get("cut"),
            "policy": obj.get("policy"),
            "refusal": obj.get("refusal"),
            "score": obj.get("score"),
            "scored": obj.get("scored"),
            "shadow": obj.get("shadow"),
            "shape": obj.get("shape"),
            "values": [RiskValue.from_dict(_item) for _item in obj["values"]] if obj.get("values") is not None else None
        })
        return _obj


