# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hanzoai.cloud.models.tax_treaty import TaxTreaty
from typing import Optional, Set
from typing_extensions import Self

class TaxW8(BaseModel):
    """
    TaxW8
    """ # noqa: E501
    birth: Optional[StrictStr] = Field(default=None, description="Birth is W-8BEN line 8, the individual's date of birth, YYYY-MM-DD.")
    capacity: Optional[StrictStr] = Field(default=None, description="Capacity is the capacity in which the signer signs for the beneficial owner — \"Director\", \"Authorized officer\". Required on a W-8BEN-E; on a W-8BEN, empty when the beneficial owner signs.")
    chapter3: Optional[StrictStr] = Field(default=None, description="Chapter3 is W-8BEN-E line 4. A W-8BEN's beneficial owner is an individual and states none.")
    chapter4: Optional[StrictStr] = Field(default=None, description="Chapter4 is W-8BEN-E line 5, the FATCA status.")
    country: Optional[StrictStr] = Field(default=None, description="Country is line 2: the country of citizenship (W-8BEN) or of incorporation or organization (W-8BEN-E), ISO 3166-1 alpha-2.")
    giin: Optional[StrictStr] = Field(default=None, description="GIIN is W-8BEN-E line 9a, when the chapter 4 status carries one.")
    no_foreign_tin: Optional[StrictBool] = Field(default=None, description="NoForeignTIN is W-8BEN line 6b / W-8BEN-E line 9b's alternative: the jurisdiction of residence does not require or issue a foreign TIN.", alias="noForeignTin")
    treaty: Optional[TaxTreaty] = Field(default=None, description="Treaty is the claim of treaty benefits (W-8BEN Part II lines 9-10, W-8BEN-E Part III lines 14-15), when one is made.")
    __properties: ClassVar[List[str]] = ["birth", "capacity", "chapter3", "chapter4", "country", "giin", "noForeignTin", "treaty"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaxW8 from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of treaty
        if self.treaty:
            _dict['treaty'] = self.treaty.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaxW8 from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "birth": obj.get("birth"),
            "capacity": obj.get("capacity"),
            "chapter3": obj.get("chapter3"),
            "chapter4": obj.get("chapter4"),
            "country": obj.get("country"),
            "giin": obj.get("giin"),
            "noForeignTin": obj.get("noForeignTin"),
            "treaty": TaxTreaty.from_dict(obj["treaty"]) if obj.get("treaty") is not None else None
        })
        return _obj


