# coding: utf-8

"""
    Hanzo Cloud API

    The Hanzo Cloud API as a customer calls it: every operation under /v1/ except the operator's admin product, relay routes, legacy spellings and capabilities still reached by flag. Tagged by product: the first path segment after /v1/.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class TrainClaimed(BaseModel):
    """
    TrainClaimed
    """ # noqa: E501
    coordinator: Optional[StrictStr] = Field(default=None, description="Coordinator is where a join task reaches its lead.")
    device: Optional[StrictStr] = Field(default=None, description="Device is the accelerator kind it runs on, and Devices how many of them.")
    devices: Optional[StrictInt] = None
    held: Optional[StrictInt] = Field(default=None, description="Held is the device-seconds held for it. The cloud meters the task by the clock and stops its job before it runs past them.")
    id: Optional[StrictStr] = Field(default=None, description="ID names the task.")
    job: Optional[StrictStr] = Field(default=None, description="Job names its job.")
    lease: Optional[StrictStr] = Field(default=None, description="Lease authenticates every report for the task; it is answered once.")
    report: Optional[StrictInt] = Field(default=None, description="Report is the most seconds that may pass between its reports.")
    role: Optional[StrictStr] = Field(default=None, description="Role is lead or join.")
    __properties: ClassVar[List[str]] = ["coordinator", "device", "devices", "held", "id", "job", "lease", "report", "role"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TrainClaimed from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TrainClaimed from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "coordinator": obj.get("coordinator"),
            "device": obj.get("device"),
            "devices": obj.get("devices"),
            "held": obj.get("held"),
            "id": obj.get("id"),
            "job": obj.get("job"),
            "lease": obj.get("lease"),
            "report": obj.get("report"),
            "role": obj.get("role")
        })
        return _obj


